version: "3.9"
services:
  app:
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    build: .
    entrypoint: ./entrypoint.sh
    working_dir: /app
    command: "bundle exec puma -C puma.rb"
    volumes:
      - .:/app