version: "3.9"
services:
  app:
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    build: .
    entrypoint: ./entrypoint.sh
    working_dir: /app
    command: "bundle exec puma -C puma.rb"
    volumes:
      - .:/app
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: meli_log_development
    volumes:
      - "./mongo:/etc/mongo"
